### ISSUE TITLE
Control pauses between words

### ISSUE THREAD

**Issue by nikich340** [CorentinJ/Real-Time-Voice-Cloning#291] opened 2020-03-03 07:35 UTC
Is there any way to make pauses between words bigger, words stick together and pronounced too quick. Can I insert extra pauses between words using some punctuation signs (commas, for example) or somethings else?

I can do it manually in audio editor later, but it is more complicated than add normal pauses during synthesis.

**Comment by favarete** [comment] 2020-03-14 17:48
New lines add a short break to the audio flow, so you can break the line where you need pauses, the more line breaks, the bigger is the pause.

**Comment by nikich340** [comment] 2020-03-19 01:07
> New lines add a short break to the audio flow, so you can break the line where you need pauses, the more line breaks, the bigger is the pause.

But if I use short line then all the audio will be broken - strange noises and pauses includes in it.

**Comment by macriluke** [comment] 2020-04-07 17:29
Long story short, you'll have to train up your own synthesizer model using a dataset of fully transcribed audio (with punctuation) from many speakers, with many hours of clips of many different lengths. You'll need to train this on a machine with well-endowed GPU specs.

The work-around is to find the sweet spot for sentence lengths the model is comfortable with generating and use line breaks. too short or too long, you'll get the long pauses and strange windy noises.

**Comment by blue-fish** [comment] 2020-07-13 01:00
Closing this as a duplicate of #53 (also see #411). Thank you @macriluke for the helpful information.

**Closed by blue-fish** 2020-07-13 01:00 UTC
