### ISSUE TITLE
Some error.

### ISSUE THREAD

**Issue by snaildos** [CorentinJ/Real-Time-Voice-Cloning#240] opened 2019-12-03 09:12 UTC
Hey, I need some help. after running:
python demo_cli.py
I get this:
Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\Voice Cloner\Real-Time-Voice-Cloning\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\Voice Cloner\Real-Time-Voice-Cloning\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\Voice Cloner\Real-Time-Voice-Cloning\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\Voice Cloner\Real-Time-Voice-Cloning\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\Voice Cloner\Real-Time-Voice-Cloning\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
  File "C:\Python37\lib\site-packages\tensorflow\contrib\__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "C:\Python37\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "C:\Python37\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 91, in <module>
    from tensorflow.contrib.rnn.python.ops.lstm_ops import *
  File "C:\Python37\lib\site-packages\tensorflow\contrib\rnn\python\ops\lstm_ops.py", line 298, in <module>
    @ops.RegisterGradient("BlockLSTM")
  File "C:\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 2489, in __call__
    _gradient_registry.register(f, self._op_type)
  File "C:\Python37\lib\site-packages\tensorflow_core\python\framework\registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register C:\\Python37\\lib\\site-packages\\tensorflow_core\\python\\framework\\registry.py:66)"

**Comment by blue-fish** [comment] 2020-07-05 08:59
Duplicate of #178, root cause is using tensorflow 2.0 when the repo requires 1.x. The suggestion is to pull the latest version of the code, reinstall the requirements and try again. The current toolbox uses tensorflow 1.15.

**Closed by blue-fish** 2020-07-05 08:59 UTC
