### ISSUE TITLE
Slow training on Tesla P40 

### ISSUE THREAD

**Issue by wy192** [CorentinJ/Real-Time-Voice-Cloning#740] opened 2021-04-22 12:00 UTC
![image](https://user-images.githubusercontent.com/20884858/115710754-45264780-a3a5-11eb-896e-7ddcdf7eb0f8.png)

**Comment by wy192** [comment] 2021-04-22 12:01
![image](https://user-images.githubusercontent.com/20884858/115710923-7f8fe480-a3a5-11eb-8e5b-41a3eef1b4ff.png)

**Comment by blue-fish** [comment] 2021-05-30 07:35
Duplicate of #700, let's collect all the information about slow training and possible fixes there. Thanks for reporting the issue.

**Closed by blue-fish** 2021-05-30 07:35 UTC
