### ISSUE TITLE
How to make voices sound better?

### ISSUE THREAD

**Issue by Traincraft101** [CorentinJ/Real-Time-Voice-Cloning#197] opened 2019-11-12 23:14 UTC
Whenever I use the toolbox to make a voice, it sounds not even close to being as good as the demo video was. I tried using the LibreSpeech dataset, LJspeech1.1, and I used high quality wave files, yet it still sounds like a person dying of pneumonia.
Here's what I mean.

Demo video: https://www.youtube.com/watch?v=-O_hYhToKoA&list=WL&index=3&t=85s
My results: https://www.youtube.com/watch?v=_gj30DZ4jLg

The only difference I see in the demo video is that @CorentinJ seems to be using a different vocoder called "gen_s_mel_raw". Where would I get this?

**Comment by rfwatkins** [comment] 2019-11-14 21:37
Your GLaDOS examples illustrate the importance of trying a number of samples from the same voice.  For mysterious reasons, some samples give much better results than others.  Really one just needs to keep trying, and usually you'll eventually hit a really decent sample that gives nice synthesis results.  Shorter samples often work better than long ones in my experience thus far. Gaps and sibilant white noise happen when the text sample you're trying to synthesize is too short - too long and it can end up as high-speed babble.

**Comment by blue-fish** [comment] 2020-07-05 10:45
Closing this as a duplicate of #162 , @Traincraft101 good observation on the pretrained vocoder as `gen_s_mel_raw` though I am doubtful that the entire performance difference could be attributed to the vocoder.

**Closed by blue-fish** 2020-07-05 10:45 UTC

**Comment by michael-ts** [comment] 2022-10-03 16:03
I read this and the linked issue but I couldn't find the answer to "how do I get the gen_s_mel_raw vocoder".  I only get two options: "default" and "Griffin-Lim".  The latter sounds significantly better than "default" and about the same quality as in the video, i.e. not really sounding much like the input source.  I feel like with "gen_s_mel_raw" it would reach the quality shown in the demo video.

So if I may ask, what am I missing that I do not see the "gen_s_mel_raw" vocoder?  I have installed and am using both  train-clean-100 and train-clean-360 as recommended, and am passing the path to the Dataset directory on the command line (and train-clean-100 shows up under Dataset in the upper left (Don't see train-clean-360 anywhere though)

**Comment by michael-ts** [comment] 2022-10-04 01:14
I also installed the train-clean-500 files under Dataset and still only see "default" for "Encoder" and "Synthesizer" and only "default" and "Griffin-Lim" for Vocoder.  In the video there was a veritable cornucopia of Vocoder choices, how do I get those?
