### ISSUE TITLE
Toolbox can't vocode.

### ISSUE THREAD

**Issue by bllurr** [CorentinJ/Real-Time-Voice-Cloning#386] opened 2020-06-27 09:13 UTC
So... I have managed to successfully install the toolbox with other components as well such as CUDA, cuDNN, Pytorch, and pre-trained models. I opened the toolbox and record my own voice, but when I click synthesize and vocode, nothing happens on the toolbox, but in cmd, there is an error message:
```
Traceback (most recent call last):
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 77, in <lambda>
    func = lambda: self.load_from_browser(self.ui.browse_file())
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 119, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 111, in load_preprocess_wav
    wav = librosa.load(str(fpath), hparams.sample_rate)[0]
  File "C:\Users\fcbge\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 162, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\fcbge\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 186, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\fcbge\AppData\Local\Programs\Python\Python37\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
```

**Comment by blue-fish** [comment] 2020-06-27 09:43
Have you tried demo_cli.py? I have never used the toolbox. Likely some part of it needs to be updated for compatibility with the recent changes.

**Comment by blue-fish** [comment] 2020-06-27 09:44
Take a look at [https://github.com/librosa/librosa/issues/219](https://github.com/librosa/librosa/issues/219), you may need to install some codecs.

**Comment by bllurr** [comment] 2020-06-27 11:48
@blue-fish  now this happens:
```
Traceback (most recent call last):
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 87, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 173, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 59, in __init__
    self.session = tf.compat.v1.Session(config=config)
  File "C:\Users\fcbge\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1585, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "C:\Users\fcbge\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 699, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
```

**Comment by blue-fish** [comment] 2020-06-27 12:00
When you install a tensorflow binary it is only compatible with a single CUDA driver version, and it appears you have a mismatch. Here is a compatibility table: [https://stackoverflow.com/a/50622526](https://stackoverflow.com/a/50622526)

Pick one (listed easiest to hardest):
1. Instead of running toolbox, run demo_cli.py with --cpu option
2. Update your CUDA driver to match the version that is supported by your tensorflow.
3. Build tensorflow from source with support for the specific CUDA driver already installed.

**Comment by bllurr** [comment] 2020-06-27 12:30
I tried option no 2 but it shows the same error, I want to try option 1  but how do you use the CPU option?

**Comment by blue-fish** [comment] 2020-06-27 12:44
`python demo_cli.py --cpu`

**Comment by bllurr** [comment] 2020-06-27 12:49
I tried that but this happens:
```
Traceback (most recent call last):
  File "demo_cli.py", line 95, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "C:\Users\fcbge\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 59, in __init__
    self.session = tf.compat.v1.Session(config=config)
  File "C:\Users\fcbge\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1585, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "C:\Users\fcbge\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 699, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
```

**Comment by blue-fish** [comment] 2020-06-27 16:10
I'm about out of ideas...
1. Try uninstalling `tensorflow-gpu`
2. What GPU do you have?
3. Can you list out your installed packages and their versions? If you are using pip or conda, `pip list` or `conda list` will return this information.

**Comment by blue-fish** [comment] 2020-07-04 15:04
Hi @bllurr , did you get it to work?

**Comment by blue-fish** [comment] 2020-07-04 15:15
The [last issue](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/386#issuecomment-650557195) is a duplicate of #321 (no solution posted). If you were able to get past that step would you please share your solution?

**Comment by blue-fish** [comment] 2020-07-04 15:19
You might also want to check out #398 as an potential alternative if you continue to have issues with the setup.

**Comment by blue-fish** [comment] 2020-07-10 06:16
Hi @bllurr , I am closing this issue because it has not been updated in a while. I hope you were able to get the toolbox to work. It would be nice to know the current status. Feel free to reopen this issue if you have any questions or comments.

**Closed by blue-fish** 2020-07-10 06:16 UTC

**Comment by sahil-dhuri** [comment] 2022-02-15 12:13
yaa, m to facing same argument problem
![image](https://user-images.githubusercontent.com/58507710/154059995-dedeea31-1fec-4b8b-96c6-6d1fa0ce1710.png)
