### ISSUE TITLE
demo_cli.py only outputs 6 or 7 seconds of audio

### ISSUE THREAD

**Issue by genewitch** [CorentinJ/Real-Time-Voice-Cloning#206] opened 2019-11-14 07:11 UTC
Been using it on an AWS g4dn.xlarge instance (tesla T4 gpu) ubuntu 18.04 with virtualenv, python3.7, ffmpeg, etc installed.

no matter what source file i use, the output is only 6 or 7 seconds, and if the text i type in makes the file longer than that, it starts mangling the output about midway through. I started looking through the source for the encoder/etc and couldn't see anything with this as a hard limit.

If anyone has forked this to use 1 source file and make longer clips output, please let me know. Thank you!
edit: I should note that it seems like if i have a slightly longer text length that the outputted audio seems spoken faster. Shorter lengths of text sound more natural (but still quite fast) and longer lengths of texts either start garbling/making random noises around the halfway mark or truncate at 6 or 7 seconds - and they are spoken much faster, twice as fast, perhaps.

edit2: I think the issue is with the spectrogram creation, as no matter what i set the vocoder settings to the only thing that changes is how long the processing takes, and not the resultant audio length. 
I've gone through most of the files now and i didn't notice anything apparent that would make the spectrogram only 6-7 seconds long. I'll keep digging.

P.S. i forgot if proper form on github is to edit OP or post replies.

**Comment by genewitch** [comment] 2019-11-14 07:17
I should note that it seems like if i have a slightly longer text length that the outputted audio seems spoken faster. Shorter lengths of text sound more natural (but still quite fast) and longer lengths of texts  either start garbling/making random noises around the halfway mark or truncate at 6 or 7 seconds - **and** they are spoken much faster, twice as fast, perhaps.

**Comment by genewitch** [comment] 2019-11-14 09:10
if i put 7 words in, the file is 7 seconds long, with a long delay between each. if i put 120 words in, the file is 28 seconds long, but is completely unintelligible after 4 seconds. 40 words is also 28 seconds long but it stays intelligible for about 6-8 seconds. both of the latter text inputs speak MUCH faster. Is it the hdparms.py file that i need to spend more time looking at?

i tried editing spec = spec[0] to do the concatenate per the section above. 
`spec =  np.concatenate(specs, axis=1)`

admittedly i have no idea what i am doing nor how to proceed. Thanks for anyone's time.

**Comment by blue-fish** [comment] 2020-07-10 16:07
@genewitch I am going to close this as a duplicate of issues #53 (for short text inputs causing gaps) and #347 (long text inputs causing fast or garbled output). As you have discovered, the model is optimized for outputs about 5-6 seconds in length and degrades when the inputs are deviate too far from this.

I find it is easier to work around this in the toolbox where you can paste a long text and manually add line breaks to break it into 5-6 second chunks.

**Closed by blue-fish** 2020-07-10 16:07 UTC
