### ISSUE TITLE
Error when running demo_cli.py. Please Help!

### ISSUE THREAD

**Issue by CosmonautNinja** [CorentinJ/Real-Time-Voice-Cloning#344] opened 2020-05-14 14:18 UTC
When I run demo_cli.py I get this error:

Traceback (most recent call last): File ".\demo_cli.py", line 96, in <module> mels = synthesizer.synthesize_spectrograms(texts, embeds) File "D:\Users\Jay\Desktop\Deepvoice\synthesizer\inference.py", line 77, in synthesize_spectrograms self.load() File "D:\Users\Jay\Desktop\Deepvoice\synthesizer\inference.py", line 58, in load self._model = Tacotron2(self.checkpoint_fpath, hparams) File "D:\Users\Jay\Desktop\Deepvoice\synthesizer\tacotron2.py", line 28, in __init__ split_infos=split_infos) File "D:\Users\Jay\Desktop\Deepvoice\synthesizer\models\tacotron.py", line 146, in initialize zoneout=hp.tacotron_zoneout_rate, scope="encoder_LSTM")) File "D:\Users\Jay\Desktop\Deepvoice\synthesizer\models\modules.py", line 221, in __init__ name="encoder_fw_LSTM") File "D:\Users\Jay\Desktop\Deepvoice\synthesizer\models\modules.py", line 114, in __init__ self._cell = tf.contrib.cudnn_rnn.CudnnLSTM(num_units, name=name) TypeError: __init__() missing 1 required positional argument: 'num_units'

Can somone help fix it?

**Comment by me16io** [comment] 2020-05-16 05:01
I have found that the error is from the program  synthesizer\models\modules.py, it appears to try and create a ZoneoutLSTMCell at line 222 and 224, however when initialized on line 102 a required argument num_units is needed. This value is not being passed in on creation at line 222 or 224 and as such is failing due to the improper number of variables. Sadly I am unaware of the fix for this currently. I will be looking into this further at a later date. However i figured I would point out where this error is being created if someone else is able to fix it prior.

**Comment by me16io** [comment] 2020-05-16 16:26
The error is coming from the file synthesizer\models\modules.py on line 115 an if statement is checking if torch is available and assigning self.cell  to either a CudnnLSTM or a LSTMBlockCell. The problem is that CudnnLSTM requires both num_layers num_units. so the num_units being passed in is seen as units. I am unsure of what value should be passed in for the layer. However a temp fix is to remove the if else statement and the line 
self._cell = tf.contrib.cudnn_rnn.CudnnLSTM(num_units, name=name) and only leave the line 
self._cell = tf.contrib.rnn.LSTMBlockCell(num_units=num_units, name=name) as the LSTMBlockCell does not require the num_layer parameter. A better fix however would be to pass in 
self._cell = tf.contrib.cudnn_rnn.CudnnLSTM(num_layers, num_units, name=name) 
on line 115 if that can be found.

**Comment by blue-fish** [comment] 2020-06-24 08:39
Closing this issue as the bug is fixed with #374

**Closed by blue-fish** 2020-06-24 08:39 UTC
