### ISSUE TITLE
Attempt to run demo_cli.py difficulty

### ISSUE THREAD

**Issue by gentlemancmm** [CorentinJ/Real-Time-Voice-Cloning#233] opened 2019-11-27 06:55 UTC
Hi! I am attempting to run your software, but when I run the demo_cli.py test, I see this trace call: Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\comes\OneDrive\Desktop\VoiceClone\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\comes\OneDrive\Desktop\VoiceClone\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\comes\OneDrive\Desktop\VoiceClone\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\comes\OneDrive\Desktop\VoiceClone\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "C:\Users\comes\OneDrive\Desktop\VoiceClone\Real-Time-Voice-Cloning-master\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 91, in <module>
    from tensorflow.contrib.rnn.python.ops.lstm_ops import *
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\lstm_ops.py", line 298, in <module>
    @ops.RegisterGradient("BlockLSTM")
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 2489, in __call__
    _gradient_registry.register(f, self._op_type)
  File "C:\Users\comes\Anaconda3\lib\site-packages\tensorflow_core\python\framework\registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register C:\\Users\\comes\\Anaconda3\\lib\\site-packages\\tensorflow_core\\python\\framework\\registry.py:66)"

You have any advice or thought on what is the problem? I am a computer science major but this software is very new to me and I see no documentation online for this issue.

**Comment by blue-fish** [comment] 2020-07-05 08:58
Duplicate of #178, root cause is using tensorflow 2.0 when the repo requires 1.x. The suggestion is to pull the latest version of the code, reinstall the requirements and try again. The current toolbox uses tensorflow 1.15.

**Closed by blue-fish** 2020-07-05 08:58 UTC
