### ISSUE TITLE
Issues with outputs of short and long texts

### ISSUE THREAD

**Issue by kkprabhu** [CorentinJ/Real-Time-Voice-Cloning#459] opened 2020-07-30 14:05 UTC
Hello, and thank you for this great work @CorentinJ 
I have below few observations. Wanted to bring them to your notice and seek your advice in fixing them.
1) For a shorter input text (~<25 characters), the generated audio has gaps/noise in between words. Is there any way to prevent it(happens consistently)?
2) For longer input text(between 25 to 120 characters), the words are skipped in between. This is not consistent but happens quite frequently. Any reason for this and any way to prevent this?
3) For very long input text(>120 characters with multiple sentences), the generated output starts with a normal speed and then the speed increases to an extent it becomes difficult to comprehend. Any solution to this?

I am using the pre-trained models you have published in this repo.
Appreciate if you can share your thoughts and advice.
Thanks in advance!

**Comment by blue-fish** [comment] 2020-07-30 14:13
1. See #53. It gets a little better with a LibriTTS-trained model: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/449#issuecomment-665645153 
2. Have not seen this before, can you try to find an input sequence + random seed that does this? And provide the source audio file for the embed.
3. See #347 

Also see #411 for discussion about some things that should be changed or improved.

**Comment by blue-fish** [comment] 2020-08-07 07:42
@kkprabhu Closing as duplicate of #411. You are welcome to reopen this issue if you have audio samples and a reproducible test case for the number 2 item (skipped words).

**Closed by blue-fish** 2020-08-07 07:42 UTC
