### ISSUE TITLE
help!! pls  i,ve installed pytorch, ffmpeg in windows environment. and required pip packages. but still 

### ISSUE THREAD

**Issue by ACG-MM** [CorentinJ/Real-Time-Voice-Cloning#450] opened 2020-07-25 19:42 UTC
E:\AI Tool\Real-Time-Voice-Cloning-master>python demo_cli.py
2020-07-26 20:20:27.179858: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-26 20:20:27.181928: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "demo_cli.py", line 4, in <module>
    from synthesizer.inference import Synthesizer
  File "E:\AI Tool\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "E:\AI Tool\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "E:\AI Tool\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "E:\AI Tool\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 4, in <module>
    from synthesizer.models.helpers import TacoTrainingHelper, TacoTestHelper
  File "E:\AI Tool\Real-Time-Voice-Cloning-master\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by ACG-MM** [comment] 2020-07-26 14:11
the cudart64_101.dll in . and i tried install tensorflow-gpu still error above. and when i try pip install -r requirements.txt  it always shows Could not find a version that satisfies the requirement tensorflow==1.15

**Comment by blue-fish** [comment] 2020-07-26 14:14
>  it always shows Could not find a version that satisfies the requirement tensorflow==1.15

What version of python do you have? The toolbox requires python 3.6 or 3.7.

Tensorflow==1.15 is not available for python 3.8 or newer.

**Comment by ACG-MM** [comment] 2020-07-26 15:01
> > it always shows Could not find a version that satisfies the requirement tensorflow==1.15
> 
> What version of python do you have? The toolbox requires python 3.6 or 3.7.
> 
> Tensorflow==1.15 is not available for python 3.8 or newer.



> > it always shows Could not find a version that satisfies the requirement tensorflow==1.15
> 
> What version of python do you have? The toolbox requires python 3.6 or 3.7.
> 
> Tensorflow==1.15 is not available for python 3.8 or newer.

i do use python 3.8 and i just get it now. may this project support TF 2x?  am i have to use python 3.7

**Comment by blue-fish** [comment] 2020-07-26 15:41
Please use python 3.7. We have an issue open to make the toolbox compatible with TF 2.x: #370 , but it is not ready yet.

**Comment by blue-fish** [comment] 2020-07-26 20:29
Closing this issue as we've found out the root cause (duplicate of #401). @ACG-MM , if you have further issues with toolbox setup please open a new issue.

**Closed by blue-fish** 2020-07-26 20:29 UTC
