### ISSUE TITLE
Noise, wheezing in the output audio

### ISSUE THREAD

**Issue by nikolaev1ma** [CorentinJ/Real-Time-Voice-Cloning#713] opened 2021-03-26 17:29 UTC
Hi! Almost all the output audio that I received had a low voice frequency, and noise could occur in the middle of the voice. On many synthesized audio, the voice had a "hoarseness".
 
As the source audio, I tried many different voices, many of them with a high-pitched voice. 
What could be the problem? Is this an inaccuracy of the model or my mistake? 

Thank you in advance for your help!

**Comment by blue-fish** [comment] 2021-04-01 00:20
If your source audio is low quality, that may be the problem. Do you have this problem if you use the audio files bundled with the repo in the `samples` folder?

**Comment by blue-fish** [comment] 2021-04-01 00:54
Related issues: #41, #314

**Comment by blue-fish** [comment] 2021-04-04 07:17
Closed as duplicate of #41

**Closed by blue-fish** 2021-04-04 07:17 UTC
