### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found (Real-Time-Voice-Cloning-master)

### ISSUE THREAD

**Issue by pritxm** [CorentinJ/Real-Time-Voice-Cloning#407] opened 2020-07-08 06:52 UTC
PS C:\Users\Pritam> cd D:\Game\Real-Time-Voice-Cloning-master
PS D:\Game\Real-Time-Voice-Cloning-master> python demo_cli.py
2020-07-08 12:18:00.259919: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "D:\Game\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "D:\Game\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "D:\Game\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "D:\Game\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 5, in <module>
    from synthesizer.models.modules import *
  File "D:\Game\Real-Time-Voice-Cloning-master\synthesizer\models\modules.py", line 2, in <module>
    import torch
  File "C:\Users\Pritam\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\Pritam\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
PS D:\Game\Real-Time-Voice-Cloning-master>

This is what i get after i run this in Powershell. I'm pretty sure I've done everything right at every step! Can anyone figure out what may be missing here?

**Comment by blue-fish** [comment] 2020-07-08 07:18
@pritxm Looks very similar to this, could be a torch version issue. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/260#issuecomment-655039901

Could you please 1) uninstall torch, 2) visit https://pytorch.org and install the appropriate version , and try again?

**Comment by pritxm** [comment] 2020-07-08 07:36
Hey @blue-fish thank you for replying. I've uninstalled pytorch. I'm running CUDA 10.0 (as told in the Voice Clone installation guide https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/ ) But I can't find pytorch for CUDA 10.0. Which one should i get? The only CUDA options I see are 9.2
10.1
10.2
None

**Comment by blue-fish** [comment] 2020-07-08 07:48
It means that CUDA 10.0 is not available for the latest version of torch, but it is for earlier versions (which should work with the toolbox).

Try this:
```
pip install  torch==1.4.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html
```

There is a chance 1.4.0 is not available for Windows, in which case try torch==1.2.0+cu100 instead.

**Comment by pritxm** [comment] 2020-07-08 07:51
ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cu100 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.0+cpu, 1.2.0+cu92, 1.3.0, 1.3.0+cpu, 1.3.0+cu92, 1.3.1, 1.3.1+cpu, 1.3.1+cu92, 1.4.0, 1.4.0+cpu, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92)
ERROR: No matching distribution found for torch==1.4.0+cu100




 ERROR: Could not find a version that satisfies the requirement torch==1.2.0+cu100 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.0+cpu, 1.2.0+cu92, 1.3.0, 1.3.0+cpu, 1.3.0+cu92, 1.3.1, 1.3.1+cpu, 1.3.1+cu92, 1.4.0, 1.4.0+cpu, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92)
ERROR: No matching distribution found for torch==1.2.0+cu100
Tried both. None worked :(

**Comment by blue-fish** [comment] 2020-07-08 07:51
Since the installation guide was written, we added CPU support so you're not required to match the torch and CUDA versions. It provides a nice speedup but if you experience a lot of frustration at the install I would just install any recent torch and try the toolbox. Then at a later date, fix your setup to get the GPU speedup if you really want to dive into training or generating a lot of cloned speech.

**Comment by blue-fish** [comment] 2020-07-08 07:53
Interesting, I found this file and thought 1.2.0 would have CUDA 10.0 support:
https://download.pytorch.org/whl/cu100/torch-1.2.0-cp37-cp37m-win_amd64.whl

**Comment by pritxm** [comment] 2020-07-08 07:58
Thank you for the link. I'll download and try running it. While it's downloading could you please tell me how can I install it using pip install? I'm new to it.

**Comment by blue-fish** [comment] 2020-07-08 08:23
This might be able to help you with the installation: https://stackoverflow.com/a/27909082

If it doesn't work I would recommend downloading the latest torch for CPU.

**Comment by pritxm** [comment] 2020-07-08 08:51
PS D:\Game\Real-Time-Voice-Cloning-master> python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\Game\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\Game\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "D:\Game\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "D:\Game\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\Pritam\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.


:(((
What this might be any idea?

**Comment by blue-fish** [comment] 2020-07-08 08:52
Is that error message with torch 1.2.0 for CUDA 10.0?

**Comment by pritxm** [comment] 2020-07-08 08:53
Yes.

**Comment by blue-fish** [comment] 2020-07-08 09:01
Try these instructions to run the toolbox on CPU. Nothing needs to be uninstalled before starting, we will use a virtual environment.

#### Make a virtual environment and activate it:
```
python -m venv env
env\Scripts\activate.bat
```

#### Install torch for CPU and the requirements
```
pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
pip install -r requirements.txt
```

#### Run the toolbox
```
python demo_toolbox.py
```

**Comment by pritxm** [comment] 2020-07-08 09:16
DUDE! You're awesome this worked! Do I always have to create a virtual environment to use this? Or is there any other way I can play it directly? And thanks alot btw 👍 :)

**Comment by blue-fish** [comment] 2020-07-08 09:19
Glad it is working for you now :D

The virtual environment is suggested, but you don't need it if you default python environment just like the virtualenv. If you want to try GPU support again, you can `deactivate` your virtual environment and try following the quoted step in my comment here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/407#issuecomment-655384859

Seems like renaming/deleting a DLL may be all that's needed. If you don't mind could you try it just to see if that would fix it?

**Comment by pritxm** [comment] 2020-07-08 09:25
Actually I renamed it already when I was looking at the installation guide. I'll try deleting it.

**Comment by blue-fish** [comment] 2020-07-08 09:29
I wonder if the problematic DLL would have been installed when you installed torch 1.2.0 just now.

**Comment by pritxm** [comment] 2020-07-08 10:00
Could you please tell me how to set my default environment as a virtual environment?
And after setting up the virtual environment can I just type python demo_toolbox.py and play it?

**Comment by blue-fish** [comment] 2020-07-08 10:07
I take it that GPU still doesn't work?

> Could you please tell me how to set my default environment as a virtual environment?

I don't know how to automatically launch a virtual environment (but I am sure guides exist). If you only ever use python to use this toolbox, you should try uninstalling the torch 1.2.0 from your default environment and install the working torch. The virtualenv is only needed if you run other programs with conflicting requirements which make a common environment impossible.

> And after setting up the virtual environment can I just type python demo_toolbox.py and play it?

Yes, after you have activated a virtual environment with the correct requirements, the toolbox should run.

**Comment by pritxm** [comment] 2020-07-08 10:20
> I take it that GPU still doesn't work?
Actually I haven't tried it yet. Could you tell me how do I deactivate the virtual environment? 

Also I can't load any audio files on it. I can record but cannot load any of the mp3 files. 
I'm getting this  : 
Exception :  expected str, bytes or os.PathLike object, not NoneType

Would you happen to  know why is this happening?

**Comment by blue-fish** [comment] 2020-07-08 10:23
> Could you tell me how do I deactivate the virtual environment?

Type `deactivate` in your shell.

> Exception : expected str, bytes or os.PathLike object, not NoneType

Click the "Browse" button to load a file. The "Load" button only works if you specified <datasets_root> when launching the toolbox. We should disable that button when <datasets_root> is not specified.

**Comment by pritxm** [comment] 2020-07-08 10:25
Mate I'm a such a noob at this. I'm sorry. Could you please tell me how do I set the datasets root? Or what do I do to load the mp3 file?

**Comment by blue-fish** [comment] 2020-07-08 10:31
We need to make this toolbox GUI friendlier. Click the "Browse" button and select your mp3 file.

**Comment by pritxm** [comment] 2020-07-08 10:34
Nothing happens when I select an mp3 or when I load it
I get a blank exception when i click select a file and get this 
Exception : expected str, bytes or os.PathLike object, not NoneType when I load one

**Comment by blue-fish** [comment] 2020-07-08 10:38
I am pretty sure the problem is that audioread has no backend. If you look at your terminal it should have the traceback. You can solve that by installing ffmpeg on windows. Can also see #386 or librosa/librosa#219.

If you don't want to install ffmpeg, you should be able to load .wav files without ffmpeg since no conversion is needed.

**Comment by pritxm** [comment] 2020-07-08 11:06
Dude it worked! Thank you so mcuh for being so patient and helping me! Cheers man! Awesome guy! :D

**Comment by pritxm** [comment] 2020-07-08 11:07
https://www.youtube.com/watch?v=LSh2tQ6OyZs 
I was planning on doing some stuff like this

**Comment by blue-fish** [comment] 2020-07-08 16:25
You are also to be commended on your determination to get it working. Thanks for uncovering several pain points that need to be improved:

* For ease of installation, possibly suggest users to install in a virtual environment with torch+cpu, and have an separate guide for GPU support?
* Need to disable "Load" button in toolbox GUI when launched without <datasets_root> path
* Should ask users to install ffmpeg as a prerequisite to avoid audioread "no backend" issue

I am going to close this issue now that it is resolved. Best of luck on your project!

**Closed by blue-fish** 2020-07-08 16:25 UTC

**Comment by pritxm** [comment] 2020-07-09 10:34
@blue-fish do you have a twitter or anything where I can contact you?

**Comment by blue-fish** [comment] 2020-07-09 20:32
@pritxm I don't have any social media. Why don't you just message me here if needed.

**Comment by pritxm** [comment] 2020-07-10 15:22
Hey @blue-fish I was wondering how could I add other voices (accents) to the text-to-speech pretrained models?

**Comment by blue-fish** [comment] 2020-07-10 20:19
@pritxm You will need to use another dataset to continue training of the pretrained models, to fine-tune the vocoder output to have the desired accent. The dataset needs to have the accent which you wish to impart on the text-to-speech output.

We do not have any guides on how to do this and it is outside the scope for what we can provide support for. But if you succeed in doing this please follow up and let us know! Other people have requested this, in #318 and #388 .
