### ISSUE TITLE
My voice is hoarse, like electric sound

### ISSUE THREAD

**Issue by lNeverl** [CorentinJ/Real-Time-Voice-Cloning#314] opened 2020-04-08 03:53 UTC
[voicedemo.zip](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/4448082/voicedemo.zip)
Can anyone answer my question

**Comment by sjmelsom** [comment] 2020-04-14 14:47
What is your question? Did you create this clip using a model you trained yourself or using the pretrained models?

**Comment by lNeverl** [comment] 2020-04-14 15:16
> What is your question? Did you create this clip using a model you trained yourself or using the pretrained models?

thanks for the reply. I uploaded the recording as an attachment. I used a pretrained models.

**Comment by blue-fish** [comment] 2020-07-24 23:44
This occurs when the synthesizer is unable to generalize to your voice. It is either caused by the encoder or the synthesizer not having been trained on a similar voice, but I don't know which. More likely the synthesizer I think.

In any event I will close this as a duplicate of #41. Thank you for posting the sample and reporting the issue.

**Closed by blue-fish** 2020-07-24 23:44 UTC
