### ISSUE TITLE
Long gaps in output speech

### ISSUE THREAD

**Issue by morangeman** [CorentinJ/Real-Time-Voice-Cloning#324] opened 2020-04-16 00:44 UTC
I can't seem to figure out why the audio output keeps having long gaps in it, like it will say a few words then waiiiiiiiiiit and then say the rest. the waveform is blank in the middle too.

Any ideas?

**Comment by blue-fish** [comment] 2020-07-05 09:34
Closing this as a duplicate of #227 . Thank you for reporting this issue @morangeman . I also find this to be a problem.

**Closed by blue-fish** 2020-07-05 09:34 UTC
